# Algorithm for generating a target box with a rotation angle:

# Step 1. Randomly rotate the image with the bounding box (bbox) --- obtain imgR, bboxR
# Step 2. Since rotation creates blank spaces at the four corners, cropping is required.
   # Crop requirements: Must not contain blank areas, must contain the complete bounding box, and the cropped image size must be greater than size: 224*224.
   # Cropping algorithm:
    # Calculate the minimum bounding rectangle of the target box bboxR.
    # 1) If the bounding rectangle partially exceeds imgR (i.e., intersects with the blank area), return to Step 1 (maximum 10 attempts).
    # 2) If it is still within imgR, start expanding the crop region and calculate the maximum distance maxD_S that each edge S can be expanded (limited by size and target box bboxR).
       # i.e., After moving, the distance between the two intersections of S and the imgR boundary must be equal to 224 (If the movable distance contains 0, return to Step 1).
       # a. Randomly select an edge S to expand (move) outward. The moving distance is randomly chosen within the calculated maximum range [0, maxD_s], while simultaneously determining the position of the opposite edge.
       # b. After moving, the maximum moving distance of its adjacent edges needs to be updated.
        # -- The maximum expansion distance of the two adjacent edges is restricted by the two new intersections generated by S and imgR.
        # -- If the updated movable distance contains 0, return to step a.
       # c. Randomly select an edge from the remaining adjacent edges and repeat steps a and b.
       # d. Crop the expanded rectangle.

import numpy as np
import cv2, copy, math


def rotate_crop(image, bbox, max_attempts: int = 10):
    for i in range(max_attempts):
        # Step 1: Randomly rotate the image and bounding box
        angle = np.random.uniform(-180, 180)  # Random rotation angle, range can be adjusted
        img_R, bbox_R = rotate(image, bbox, angle)

        # Calculate the minimum bounding rectangle of the rotated bounding box
        min_rect = get_min_rect(bbox_R)
        rect = min_rect.copy()
        
        # Check if the bounding box intersects with the blank area
        if rect_in_imgR(rect, img_R):
            # Step 2: Expand the crop area
            crop_rect = expand_rect(rect, img_R, angle, size=224)
            if crop_rect is not None and rect_in_imgR(crop_rect, img_R):
                # Crop the image
                x, y, w, h = crop_rect
                cropped_img = img_R[y:y+224, x:x+224]
                # Update bounding box coordinates to the cropped coordinate system
                bbox_R[:, 0] -= x
                bbox_R[:, 1] -= y
                return cropped_img, bbox_R, angle
    
    # If all attempts fail, return None
    return None, None, None


def rotate(image, bbox, angle):
    """
    Rotates the image and bounding box, ensuring the rotated image contains all original content.
    
    Args:
        image: Original image
        bbox: Bounding box [x, y, w, h]
        angle: Rotation angle (in degrees)
    
    Returns:
        rotated_img: Rotated image
        rotated_bbox: Rotated bounding box vertex coordinates (relative to the new image)
    """
    h, w = image.shape[:2]
    
    # Calculate the required image size after rotation
    corners = np.array([
        [0, 0],
        [w-1, 0],
        [w-1, h-1],
        [0, h-1]
    ], dtype=np.float32)
    
    # Convert angle to radians
    angle_rad = np.deg2rad(angle)
    
    # Calculate the center of rotation (image center)
    cx, cy = w / 2, h / 2
    
    # Corners after rotation
    rotated_corners = []
    for x, y in corners:
        # Translate to origin
        x -= cx
        y -= cy
        
        # Rotate
        x_rot = x * np.cos(angle_rad) - y * np.sin(angle_rad)
        y_rot = x * np.sin(angle_rad) + y * np.cos(angle_rad)
        
        # Translate back
        x_rot += cx
        y_rot += cy
        
        rotated_corners.append([x_rot, y_rot])
    
    rotated_corners = np.array(rotated_corners)
    
    # Calculate boundaries after rotation
    x_min = np.floor(np.min(rotated_corners[:, 0]))
    y_min = np.floor(np.min(rotated_corners[:, 1]))
    x_max = np.ceil(np.max(rotated_corners[:, 0]))
    y_max = np.ceil(np.max(rotated_corners[:, 1]))
    
    # Calculate new image size
    new_width = int(x_max - x_min)
    new_height = int(y_max - y_min)
    
    # Create a new transformation matrix, considering translation
    M = cv2.getRotationMatrix2D((cx, cy), angle, 1.0)
    
    # Add translation to ensure all content is in the new image
    M[0, 2] += -x_min
    M[1, 2] += -y_min
    
    # Perform affine transformation
    rotated_img = cv2.warpAffine(image, M, (new_width, new_height), flags=cv2.INTER_LINEAR)
    
    # Rotate the bounding box
    x, y, width, height = [round(val) for val in bbox]  # Ensure values are integers
    bbox_corners = np.array([
        [x, y],
        [x + width, y],
        [x + width, y + height],
        [x, y + height]
    ])
    
    # Convert to homogeneous coordinates
    bbox_corners_h = np.hstack((bbox_corners, np.ones((4, 1))))
    
    # Apply rotation and translation transformation
    rotated_bbox_corners = np.dot(M, bbox_corners_h.T).T
    
    return rotated_img, rotated_bbox_corners


def get_min_rect(points):
    """
    Calculate the minimum bounding rectangle of a set of points.
    """
    rect = cv2.minAreaRect(points.astype(np.float32))
    box = cv2.boxPoints(rect)
    box = np.array(box, dtype=np.intp)  # Use np.intp instead of np.int0
    
    # Get the top-left and bottom-right coordinates of the rectangle
    x_min = np.min(box[:, 0])
    y_min = np.min(box[:, 1])
    x_max = np.max(box[:, 0])
    y_max = np.max(box[:, 1])
    
    return [x_min, y_min, x_max - x_min, y_max - y_min]


def rect_in_imgR(rect, image) -> bool:
    x, y, w, h = rect
    H, W, c = image.shape
    
    # Check if the pixels at the four corners are blank (black/zero)
    corners = [
        (x, y),
        (x + w - 1, y),
        (x + w - 1, y + h - 1),
        (x, y + h - 1)
    ]
    for cx, cy in corners:
        if cx < 0 or cy < 0 or cx >= W or cy >= H:
            return False
        if np.all(image[cy, cx] == 0): 
            return False
    
    return True


def expand_rect(rect, image, angle, size=224):
    """
    Expand the rectangle while satisfying the constraints.
    
    Args:
        rect: Initial rectangle [x, y, w, h]
        image: Image
        size: Minimum size requirement
    
    Returns:
        rect: Expanded rectangle, or None if conditions cannot be met
    """
    h, w = image.shape[:2]
    rect_try = copy.deepcopy(rect)
    
    min_d, max_d = get_expand_range(rect_try, 'left', (h, w), angle, size)
    if max_d < min_d or max_d < 0:
        return None

    # Randomly select expansion distance
    expansion = np.random.uniform(min_d, max_d)  
    rect_try[0] -= expansion
    
    min_d, max_d = get_expand_range(rect_try, 'top', (h, w), angle, size)
    if max_d < min_d or max_d < 0:
        return None

    expansion = np.random.uniform(min_d, max_d)  
    rect_try[1] -= expansion
        
        
    # Success
    rect_try[0] = math.floor(rect_try[0])
    rect_try[1] = math.floor(rect_try[1])
    rect_try[2] = size
    rect_try[3] = size
    return rect_try 


def get_expand_range(rect, edge, shape, angle, size: int=224) -> tuple:
    H, W = shape
    x, y, w, h = rect
    angle = (angle+180) % 90
    
    # Convert angle to radians
    angle_rad = np.deg2rad(angle)
    sin = np.sin(angle_rad)
    cos = np.cos(angle_rad)
    tan = sin / cos
    
    if W < size or H < size: return (-1, -1)
    
    # The distance formula between edge S and the image edge intersection is: dist = D / (sin_angle * cos_angle)
    # Where D is the vertical distance between edge S and the image boundary. As D gets larger (moves towards the center), dist will also gradually increase.
    # Need to ensure dist >= size
    # Therefore, D = size * sin_angle * cos_angle
    D = size * sin * cos
    if H < 2*D + size or W < 2*D + size: return(-1, -1)
    
    # Consider if the bounding box is included
    
    # [0-90] --- Other angles can be mapped to [0-90] for processing
    # Calculate the intersection of rect and the left edge of imgR (Left side)
    #   1. Two intersections on the top-left edge of imgR: only consider the top intersection of rect
    #   2. Top intersection of rect is on the top-left edge, bottom intersection is on the bottom-left edge: consider both
    #   3. Two intersections on the bottom-left edge of imgR: only consider the bottom intersection of rect
    
    # Left side
    if edge == 'left':
        cor = W * sin  # y-coordinate of the left corner of imgR on the image
        if y < cor and (y+h) < cor : # Case 1
            DL  = (cor-y) / tan
            
        elif y < cor and (y+h) > cor : # Case 2
            DL1 = (cor-y) / tan
            DL2 = (y+h-cor) * tan
            DL  = max(DL1, DL2)
            
        else: # y > cor and (y+h) > cor : # Case 3
            DL  = (y+h-cor) * tan
            
        max_d = min(x - max(DL, D), size-w)
        # Ensure right side
        min_d = max(x + size + D - W, 0)
        
        return (min_d, max_d)
            
    # Top side
    elif edge == 'top':
        cor = W * cos  # x-coordinate of the top corner of imgR on the image
        if x < cor and (x+w) < cor : # Case 1
            DL  = (cor-x) * tan
            
        if x < cor and (x+w) > cor : # Case 2
            DL1 = (cor-x) * tan
            DL2 = (x+w-cor) / tan
            DL  = max(DL1, DL2)
            
        if x > cor and (x+w) > cor : # Case 3
            DL  = (x+w-cor) / tan
            
        max_d = min(y - max(DL, D), size-h)
        
        # Ensure bottom side
        min_d = max(y + size + D - H, 0)
        
        return (min_d, max_d)